// person/vuesjs/src/components/Nav.vue
<script setup>
    const props = defineProps({
        data: Object,
        onClick: Function
    })
</script>
<template>
    <div class="expanded button-group">
        <button v-for="row in data" @click="onClick" class="button" :data-id="row.id">{{ row.firstname}}</button>
    </div>
</template>

// person/react/src/Nav.jsx
let Nav = ({data, onClick})=>{
    return (
        <div className="expanded button-group">
            {
                data.map(row =>(
                    <button key={row.id} onClick={onClick} className="button" data-id={row.id}>{row.firstname}</button>
                ))
            }
        </div>
    )
}

export default Nav
